openapi: 3.0.0
info:
  title: NameTeller API
  version: "1.0.0"
  description: "A single endpoint that returns a static greeting."
servers:
  - url: https://nameteller-api-1.onrender.com
paths:
  /hello:
    get:
      operationId: SayHelloFarook
      summary: Returns a static greeting for Farook
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello Farook, what do you want?"
