Descriptor:
  Name: NameTeller
  DisplayName: NameTeller
  Description: Returns a static greeting for Farook.
  SupportedAuthTypes:
    - None

SkillGroups:
  - Format: API
    Settings:
      OpenApiSpecUrl: https://<raw-url-to-your-openapi.yaml>
