Descriptor:
  Name: NameTeller
  DisplayName: NameTeller
  Description: Returns a static greeting for Farook.
  SupportedAuthTypes:
    - None

SkillGroups:
  - Format: API
    Settings:
      OpenApiSpecUrl: https://raw.githubusercontent.com/yaserfarook1/nameteller_api/main/openapi.yaml

